[package]
name = "cmreader"
version = "0.1.0"
authors = ["Max Rink <29183162+Mwjrink@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
interop = { path = "../interop" }