[package]
name = "cmwriter"
version = "0.1.0"
authors = ["Max Rink <29183162+Mwjrink@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rand = "0.8.4"
interop = { path = "../interop" }
ultraviolet = { version = "0.10.0", features = ["bytemuck"] }
foldhash = "0.1.5"
metis = { version = "0.2.2", features = ["vendored"] }
graph = "0.3.1"
graph_builder = "0.4.1"
