[package]
name = "cmwriter"
version = "0.1.0"
authors = ["Max Rink <29183162+Mwjrink@users.noreply.github.com>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# rand = "0.8.4"
interop = { path = "../interop" }
ahash = "0.8.11"

